apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: mukul7661/fastapi-huey-app:latest
          ports:
            - containerPort: 80
        - name: huey-consumer
          image: mukul7661/fastapi-huey-app:latest
          command: ["python"]
          args: ["-m", "huey.bin.huey_consumer", "main.huey"]
