# redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis # Ensure this is indented correctly
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
